import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About/About'
import Card from '../components/Cards/Card'
import CircleIndicator from '../components/CircleIndicator'
import Hero from '../components/Hero/Hero'
import List from '../components/Navigation/List'
import Navigation from '../components/Navigation/Navigation'
import Team from '../components/Team/Team'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Castaar | rebuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <CircleIndicator/>

        <Navigation />

        <section className={styles.hero}>
          <Hero/>
        </section>

        <section>
          <Team />
        </section>

        <section className={styles.about}>
          <About/>
        </section>

        <section className={styles.slider}>
          <div className={styles.container}>
            <Card title='test' />
          </div>
        </section>
      </main>


      <footer className={styles.footer}>
          <span className={styles.logo}>
            <p>Site by Tim De Saeger</p>
          </span>
      </footer>
    </div>
  )
}
