import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About/About'
import Card from '../components/Cards/Card'
import CircleIndicator from '../components/CircleIndicator'
import Hero from '../components/Hero/Hero'
import List from '../components/Navigation/List'
import Navigation from '../components/Navigation/Navigation'
import Services from '../components/services/Services'
import Team from '../components/Team/Team'
import Work from '../components/Work/Work'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Castaar | rebuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <CircleIndicator/>

        <Navigation />

        <section className={styles.hero}>
          <Hero/>
        </section>

        <section className={styles.section}>
          <About/>
        </section>

        <section className={styles.section}>
          <Work/>
        </section>

        <section className={styles.section}>
          <Services/>
        </section>
      </main>


      <footer className={styles.footer}>
          <span className={styles.logo}>
            <h2 className={styles.subtitle}>X<span className={styles.dot}>X</span>X<br/>Bizzekes</h2>
            <p>Site by Tim De Saeger</p>
          </span>
      </footer>
    </div>
  )
}
